version: '3.8'
services:
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    expose:
      - "8080"  # Only expose internally for NGINX to access
    depends_on:
      - nats
    environment:
      - NATS_URL=nats://nats:4222
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
      restart_policy:
        condition: on-failure
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8222"]
      interval: 30s
      timeout: 10s
      retries: 5

  registry-service:
    build:
      context: ./registry-service
      dockerfile: Dockerfile
    expose:
      - "8081"  # Only expose internally for NGINX to access
    depends_on:
      - nats
    environment:
      - NATS_URL=nats://nats:4222
      - SERVER_ADDRESS=:8081
      - BUCKET_NAME=functions
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
      restart_policy:
        condition: on-failure
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8222"]
      interval: 30s
      timeout: 10s
      retries: 5

  spawner-service:
    build:
      context: ./spawner-service
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Access to the Docker daemon
    expose:
      - "8082"
    depends_on:
      - nats
    environment:
      - NATS_URL=nats://nats:4222
      - MAX_CONTAINERS=5
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8222"]
      interval: 30s
      timeout: 10s
      retries: 5

  nats:
    image: nats:latest
    expose:
      - "4222"  # Expose NATS for external and internal communication
    ports:
      - "4222:4222"  # External port mapped to NATS
      - "8222:8222"  # Enable monitoring on port 8222
    command:
      - "--jetstream"
      - "--store_dir=/data/jetstream"  # Directory for JetStream data
      - "--http_port=8222"  # Enable monitoring on port 8222
    volumes:
      - ./nats-data:/data  # Persistent storage for JetStream
    networks:
      - app-network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - auth-service
      - registry-service
    ports:
      - "4000:4000"  # External port mapped to auth-service
      - "5000:5000"  # External port mapped to registry-service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
