services:
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - nats
    environment:
      - NATS_URL=nats://nats:4222

  registry-service:
    build:
      context: ./registry-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - nats
    environment:
      - NATS_URL=nats://nats:4222
      - SERVER_ADDRESS=:8081
      - BUCKET_NAME=functions

  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"
    command:
      - "--jetstream"
      - "--store_dir=/data/jetstream"  # Directory for JetStream data
    volumes:
      - ./nats-data:/data  # Persistent storage for JetStream
