services:
  auth-service:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - nats
    environment:
      - NATS_URL=nats://nats:4222

  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"
    command:
      - "--jetstream"
      - "--store_dir=/data/jetstream"  # Directory for JetStream data
    volumes:
      - ./nats-data:/data  # Persistent storage for JetStream
